services:
  - type: web
    name: expense-app-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_DIALECT
        value: postgres
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: pserv
    name: expense-app-database
    env: postgresql
    plan: free
    ipAllowList: []
    disk:
      name: expense-app-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
